version: '3'

services:
  lab6:
    container_name: lab6
    restart: always
    image: lab6
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    #networks:
    #  - mynetwork

  db:
    container_name: db
    restart: always
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "x30r0YvE"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    #networks:
    #  - mynetwork

#networks:
#  mynetwork: